baseURL = 'https://rxluk.github.io/dragon-shell/'
languageCode = 'en-us'
title = 'ğŸ›¡ï¸ Dragon Shell'
theme = 'hugo-theme-island'
summaryLength = 128

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 0
    title = "ğŸ›¡ï¸ Dragon Shell"
    contentDir = "content"
    [languages.en.params]
      dateFormat = "Jan 02, 2006"
      description = "Insights and analyses on cybersecurity."

  [languages.pt]
    languageCode = "pt"
    languageName = "Portuguese" 
    weight = 10
    title = "ğŸ›¡ï¸ Dragon Shell"
    contentDir = "content"
    [languages.pt.params]
      dateFormat = "02/01/2006"
      description = "AnÃ¡lises e insights sobre ciberseguranÃ§a."

[pagination]
  disableAliases = false
  pagerSize = 5
  path = "page"

[permalinks]
  authors = "/u/:slug/"

[Taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.highlight]
      style = "github"
      noClasses = false