[[main]]
  identifier = "menu.home"
  name = "Home"
  pageRef = "/"
  weight = 10
    [[main.params]]
      icon = "home"
[[main]]
  identifier = "menu.docs"
  name = "Documentos"
  pageRef = "/docs"
  weight = 20
    [[main.params]]
      icon = "question-mark-circle"
[[main]]
  identifier = "menu.tags"
  name = "Tags"
  pageRef = "/tags"
  weight = 30
    [[main.params]]
      icon = "tag"
[[main]]
  identifier = "menu.archives"
  name = "Arquivos"
  pageRef = "/archives"
  weight = 40
    [[main.params]]
      icon = "archive-box"
[[main]]
  identifier = "menu.authors"
  name = "Autor"
  pageRef = "/authors"
  weight = 50
    [[main.params]]
      icon = "user-circle"
[[main]]
  identifier = "menu.github"
  name = "hugo-theme-island repo on Github"
  url = "https://github.com/rxluk"
  weight = 50
    [[main.params]]
      icon = "bs/github"
      target = "_blank"
